# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.admin.category:
          class: AppBundle\Admin\CategoryAdmin
          arguments: [~, AppBundle\Entity\Category, SonataAdminBundle:CRUD ]
          tags:
              - { name: sonata.admin, manager_type: orm, group: Menu, label: Category }

    app.admin.blog:
          class: AppBundle\Admin\BlogPageAdmin
          arguments: [~, AppBundle\Entity\BlogPage, SonataAdminBundle:CRUD ]
          tags:
              - { name: sonata.admin, manager_type: orm, group: Menu, label: Blog }
